### ISSUE TITLE
API Updated

### ISSUE THREAD

**Issue by orhanayd** [hammamaburaidi/DepremBilgisi#1]
https://github.com/hammamaburaidi/DepremBilgisi/blob/4d24a0219b13ecfb6a9ab7b1771ff1d47efe5b5d/DepremBilgisi/SonDepremler.swift#L15

change with:
https://api.orhanaydogdu.com.tr/deprem/kandilli/live
Docs:
https://github.com/orhanayd/kandilli-rasathanesi-api

Best regards,

**Comment by hammamaburaidi** [comment]
Changed. 

Thank you
